name: "Build static website files"

on: ["workflow_call"]

env:
  NODE_ENV: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build deployment artifacts
        run: npm run build

      - name: Copy index to 404 backup
        run: cp index.html not_found.html
        working-directory: "./dist/"

      - name: Publish build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          if-no-files-found: error
          overwrite: true

