name: "Deploy alts-alt.neocities.org"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: a1ts-a1t/alts-alt.neocities.org/.github/workflows/build.yml@main
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: build

